language: ruby
services:
  - mongodb
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
gemfile:
  - gemfiles/activerecord_3.0.gemfile
  - gemfiles/activerecord_3.0_mongoid_2.8.gemfile
  - gemfiles/activerecord_3.1.gemfile
  - gemfiles/activerecord_3.1_mongoid_2.8.gemfile
  - gemfiles/activerecord_3.2.gemfile
  - gemfiles/activerecord_3.2_mongoid_2.8.gemfile
  - gemfiles/activerecord_4.0_mongoid_4.0.gemfile
  - gemfiles/mongoid_3.0.gemfile
  - gemfiles/mongoid_3.1.gemfile
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/activerecord_3.0.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/activerecord_3.1.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/activerecord_3.2.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/activerecord_4.0_mongoid_4.0.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/mongoid_3.0.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/mongoid_3.1.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/activerecord_3.0.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/activerecord_3.0_mongoid_2.8.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/activerecord_3.1.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/activerecord_3.1_mongoid_2.8.gemfile
